title: Sparsh Kulshrestha
description: Highly skilled and experienced cyber security professional with a proven track record of success in securing systems and data. Possesses strong analytical and problem-solving skills, coupled with a keen eye for detail and a passion for staying ahead of the latest cyber threats.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
